from jinja2 import Template
from fpdf import FPDF
import os

HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detailed Diagnostic Report (DDR)</title>
    <style>
        body { font-family: 'Helvetica', 'Arial', sans-serif; color: #333; line-height: 1.6; padding: 40px; }
        .header { text-align: center; border-bottom: 2px solid #0056b3; padding-bottom: 20px; margin-bottom: 30px; }
        h1 { color: #0056b3; margin-bottom: 5px; }
        h2 { color: #0056b3; border-bottom: 1px solid #ddd; padding-bottom: 5px; margin-top: 30px; }
        .section { margin-bottom: 30px; }
        .summary { background: #f9f9f9; padding: 20px; border-left: 5px solid #0056b3; font-style: italic; }
        .area-box { border: 1px solid #ddd; border-radius: 8px; padding: 15px; margin-bottom: 20px; background: #fff; }
        .severity { font-weight: bold; padding: 5px 10px; border-radius: 4px; display: inline-block; }
        .severity-high { background: #ffebeb; color: #d93025; }
        .severity-medium { background: #fff4e5; color: #ef6c00; }
        .severity-low { background: #e6f4ea; color: #1e8e3e; }
        .image-placeholder { background: #eee; height: 150px; display: flex; align-items: center; justify-content: center; color: #777; border: 1px dashed #ccc; margin-top: 10px; }
        .action-list { padding-left: 20px; }
        .footer { margin-top: 50px; font-size: 0.8em; color: #777; text-align: center; border-top: 1px solid #ddd; padding-top: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Detailed Diagnostic Report</h1>
        <p>Technical Inspection & Thermal Analysis Summary</p>
    </div>

    <div class="section">
        <h2>Property Issue Summary</h2>
        <div class="summary">
            {{ report.property_issue_summary }}
        </div>
    </div>

    <div class="section">
        <h2>Area-wise Observations</h2>
        {% for area in report.area_wise_observations %}
        <div class="area-box">
            <h3>{{ area.area }}</h3>
            <p><strong>Observation:</strong> {{ area.observation }}</p>
            <p><strong>Thermal Findings:</strong> {{ area.thermal_findings }}</p>
            
            {% if area.image_path %}
                <img src="{{ area.image_path }}" style="max-width: 100%; border-radius: 4px; margin-top: 10px;">
            {% else %}
                <div class="image-placeholder">Image Not Available ({{ area.image_placeholder }})</div>
            {% endif %}
        </div>
        {% endfor %}
    </div>

    <div class="section">
        <h2>Probable Root Cause</h2>
        <p>{{ report.probable_root_cause }}</p>
    </div>

    <div class="section">
        <h2>Severity Assessment</h2>
        <p>
            <span class="severity severity-{{ report.severity_assessment.level|lower }}">
                {{ report.severity_assessment.level }}
            </span>
        </p>
        <p>{{ report.severity_assessment.reasoning }}</p>
    </div>

    <div class="section">
        <h2>Recommended Actions</h2>
        <ul class="action-list">
            {% for action in report.recommended_actions %}
            <li>{{ action }}</li>
            {% endfor %}
        </ul>
    </div>

    {% if report.additional_notes %}
    <div class="section">
        <h2>Additional Notes</h2>
        <p>{{ report.additional_notes }}</p>
    </div>
    {% endif %}

    <div class="section">
        <h2>Missing or Unclear Information</h2>
        <ul>
            {% for info in report.missing_information %}
            <li>{{ info }}</li>
            {% endfor %}
        </ul>
    </div>

    <div class="footer">
        Generated by Applied AI Builder &copy; 2026
    </div>
</body>
</html>
"""

def generate_html(report_data):
    """ Generates HTML string from report data using Jinja2. """
    template = Template(HTML_TEMPLATE)
    return template.render(report=report_data)

def export_pdf(report_data, output_path):
    """ Converts report data to PDF file using fpdf2. """
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(190, 10, "Detailed Diagnostic Report", 0, 1, 'C')
    pdf.set_font("Arial", size=10)
    pdf.cell(190, 10, "Technical Inspection & Thermal Analysis Summary", 0, 1, 'C')
    pdf.ln(10)

    # Property Issue Summary
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(190, 10, "Property Issue Summary", 0, 1)
    pdf.set_font("Arial", size=11)
    pdf.multi_cell(190, 6, report_data.get('property_issue_summary', 'Not Available'))
    pdf.ln(10)

    # Area-wise Observations
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(190, 10, "Area-wise Observations", 0, 1)
    for area in report_data.get('area_wise_observations', []):
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(190, 8, area.get('area', 'Unknown Area'), 0, 1)
        pdf.set_font("Arial", size=11)
        pdf.multi_cell(190, 6, f"Observation: {area.get('observation', 'Not Available')}")
        pdf.multi_cell(190, 6, f"Thermal Findings: {area.get('thermal_findings', 'Not Available')}")
        
        image_paths = area.get('image_paths', [])
        if image_paths:
            for img_path in image_paths:
                if os.path.exists(img_path):
                    try:
                        pdf.image(img_path, w=100)
                        pdf.ln(2)
                    except:
                        pdf.multi_cell(190, 6, "[Image Processing Error]")
        else:
            pdf.multi_cell(190, 6, "[Image Not Available]")
        pdf.ln(5)
    
    # Root Cause
    pdf.ln(5)
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(190, 10, "Probable Root Cause", 0, 1)
    pdf.set_font("Arial", size=11)
    pdf.multi_cell(190, 6, report_data.get('probable_root_cause', 'Not Available'))

    # Severity
    pdf.ln(10)
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(190, 10, f"Severity Assessment: {report_data.get('severity_assessment', {}).get('level', 'Not Available')}", 0, 1)
    pdf.set_font("Arial", size=11)
    pdf.multi_cell(190, 6, report_data.get('severity_assessment', {}).get('reasoning', ''))

    # Recommendations
    pdf.ln(10)
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(190, 10, "Recommended Actions", 0, 1)
    pdf.set_font("Arial", size=11)
    for action in report_data.get('recommended_actions', []):
        pdf.multi_cell(190, 6, f"- {action}")

    # Missing Info
    pdf.ln(10)
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(190, 10, "Missing or Unclear Information", 0, 1)
    pdf.set_font("Arial", size=11)
    for info in report_data.get('missing_information', []):
        pdf.multi_cell(190, 6, f"- {info}")

    pdf.output(output_path)
    return True

def save_report(report_data, base_dir, filename="DDR_Report"):
    """ Saves both HTML and PDF versions of the report. """
    html_content = generate_html(report_data)
    
    html_path = os.path.join(base_dir, f"{filename}.html")
    pdf_path = os.path.join(base_dir, f"{filename}.pdf")
    
    with open(html_path, "w") as f:
        f.write(html_content)
        
    export_pdf(report_data, pdf_path)
    
    return html_path, pdf_path
